In [3]:
import torch

In [4]:
tensor1 = torch.tensor([1,2,3,4])
tensor1

tensor([1, 2, 3, 4])

In [10]:
tensor2 = torch.tensor([[1,2, 3], [3,4, 5]])
tensor2

tensor([[1, 2, 3],
        [3, 4, 5]])

In [6]:
tensor3 = torch.ones(5)
tensor3

tensor([1., 1., 1., 1., 1.])

In [8]:
tensor4 = torch.zeros((2,3))
tensor4

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
tensor5 = torch.rand((2,3))
tensor5

tensor([[0.3632, 0.0709, 0.1715],
        [0.7594, 0.7196, 0.6804]])

In [11]:
tensor2 * tensor5

tensor([[0.3632, 0.1418, 0.5144],
        [2.2782, 2.8785, 3.4022]])

In [12]:
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

In [13]:
A * B

tensor([[ 5, 12],
        [21, 32]])

In [14]:
torch.matmul(A, B)

tensor([[19, 22],
        [43, 50]])

In [15]:
tensor5.reshape(3,2)

tensor([[0.3632, 0.0709],
        [0.1715, 0.7594],
        [0.7196, 0.6804]])

In [16]:
tensor5.reshape(6)

tensor([0.3632, 0.0709, 0.1715, 0.7594, 0.7196, 0.6804])

In [17]:
tensor5.view(-1)

tensor([0.3632, 0.0709, 0.1715, 0.7594, 0.7196, 0.6804])

In [21]:
x1 = torch.tensor(2.0)

In [52]:
x2 = torch.tensor(2.0, requires_grad = True)

In [40]:
y1 = x1 ** 3 + 4 * x1
y1

tensor(16.)

In [53]:
y2 = x2 ** 1 + 4 * x2
y2

tensor(10., grad_fn=<AddBackward0>)

In [56]:
y2.backward()

In [58]:
y2

tensor(10., grad_fn=<AddBackward0>)

In [57]:
x2.grad

tensor(5.)

In [69]:
x3 = torch.tensor([2.0, 3.0], requires_grad = True)

In [70]:
x3

tensor([2., 3.], requires_grad=True)

In [71]:
y3 = x3 ** 2 + 2 * x3

In [72]:
y3

tensor([ 8., 15.], grad_fn=<AddBackward0>)

In [73]:
y3.sum()

tensor(23., grad_fn=<SumBackward0>)

In [74]:
y3.sum().backward()

In [75]:
y3

tensor([ 8., 15.], grad_fn=<AddBackward0>)

In [76]:
x3

tensor([2., 3.], requires_grad=True)

In [77]:
x3.grad

tensor([6., 8.])

In [84]:
x5 = torch.tensor(2.0, requires_grad = True)

In [79]:
y5 = x5 ** 1 + 4 * x5
y5

tensor(10., grad_fn=<AddBackward0>)

In [80]:
x5.grad

In [81]:
y5.backward()

In [82]:
x5.grad

tensor(5.)

In [87]:
with torch.no_grad():
    y5 = x5 ** 1 + 4 * x5
x5.grad