In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [12]:
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.layer1 = nn.Linear(2,3)
        self.layer2 = nn.Linear(3,1)

    def forward(self, x):
        print(x)
        x = self.layer1(x)
        print(x)
        x = torch.relu(x)
        print(x)
        x = self.layer2(x)
        print(x)
        return x

tensor1 = torch.tensor([1.0,2.0])
model = SimpleNN()
model.forward(tensor1)

tensor([1., 2.])
tensor([-0.8655,  0.0865,  1.2546], grad_fn=<ViewBackward0>)
tensor([0.0000, 0.0865, 1.2546], grad_fn=<ReluBackward0>)
tensor([-0.9684], grad_fn=<ViewBackward0>)


tensor([-0.9684], grad_fn=<ViewBackward0>)

In [13]:
# y = 2*x1 + 3*x2

In [14]:
x = torch.tensor([[1.0, 2.0], [2.0, 3.0], [3.0, 4.0], [4.0, 5.0]])
y = torch.tensor([[8.0], [13.0], [18.0], [23.0]]) 

In [76]:
class NNtest(nn.Module):
    def __init__(self):
        super(NNtest, self).__init__()
        # self.layer1 = nn.Linear(2,3)
        # self.layer2 = nn.Linear(3,2)
        self.layer3 = nn.Linear(2,1)
    def forward(self, x):
        # x = self.layer1(x)
        # x = torch.relu(x)
        # x = self.layer2(x)
        # x = torch.relu(x)
        x = self.layer3(x)
        print(x)
        return x

In [77]:
model = NNtest()

loss_fn = nn.MSELoss()

optimizer = optim.SGD(model.parameters(), lr = 0.001)

print(model.parameters())

epochs = 100

for i in range(1, epochs + 1):
    predictions = model(x)

    loss = loss_fn(predictions, y)

    optimizer.zero_grad()
    loss.backward()

    optimizer.step()

    if i % 20 == 0:
        print(f"epoch: {i}, loss: {loss}")

<generator object Module.parameters at 0x76b7def60890>
tensor([[-0.7891],
        [-1.0669],
        [-1.3448],
        [-1.6226]], grad_fn=<AddmmBackward0>)
tensor([[-0.3987],
        [-0.4497],
        [-0.5006],
        [-0.5516]], grad_fn=<AddmmBackward0>)
tensor([[-0.0253],
        [ 0.1406],
        [ 0.3066],
        [ 0.4726]], grad_fn=<AddmmBackward0>)
tensor([[0.3317],
        [0.7052],
        [1.0787],
        [1.4521]], grad_fn=<AddmmBackward0>)
tensor([[0.6732],
        [1.2451],
        [1.8170],
        [2.3889]], grad_fn=<AddmmBackward0>)
tensor([[0.9998],
        [1.7614],
        [2.5231],
        [3.2848]], grad_fn=<AddmmBackward0>)
tensor([[1.3121],
        [2.2552],
        [3.1984],
        [4.1415]], grad_fn=<AddmmBackward0>)
tensor([[1.6107],
        [2.7274],
        [3.8441],
        [4.9609]], grad_fn=<AddmmBackward0>)
tensor([[1.8963],
        [3.1790],
        [4.4617],
        [5.7444]], grad_fn=<AddmmBackward0>)
tensor([[2.1695],
        [3.6109],
      

In [67]:
test_data = torch.tensor([5.0, 6.0]) # 10 + 18 = 28
output = model(test_data)
output

tensor([27.9754], grad_fn=<ViewBackward0>)

Gradients for weights:
tensor([[-1.2088, -1.5505]])

Gradients for bias:
tensor([-0.3417])
