In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [11]:
class HousePrice(nn.Module):
    def __init__(self):
        super(HousePrice, self).__init__()
        self.layer1 = nn.Linear(3, 1)

    def forward(self, x):
        x = self.layer1(x)
        # x = torch.relu(x)
        # x = self.layer2(x)
        return x



In [14]:
# house data (size sq ft, bedrooms, age)
X = torch.tensor([
    [1400, 3, 20],
    [1600, 4, 15],
    [1700, 3, 10],
    [1875, 3, 5],
    [1100, 2, 25]
], dtype=torch.float32)

# Normalize the data (important for better training)
X_mean, X_std = X.mean(dim=0), X.std(dim=0)
print(X_mean, X_std)

X_norm = (X - X_mean) / X_std  # Standardization
print(X_norm)

Y = torch.tensor([[245], [312], [279], [308], [199]], dtype=torch.float32)  # Prices in $1000s

tensor([1535.,    3.,   15.]) tensor([297.6995,   0.7071,   7.9057])
tensor([[-0.4535,  0.0000,  0.6325],
        [ 0.2183,  1.4142,  0.0000],
        [ 0.5543,  0.0000, -0.6325],
        [ 1.1421,  0.0000, -1.2649],
        [-1.4612, -1.4142,  1.2649]])


In [35]:
model = HousePrice()

loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr = 0.01)

epochs = 250

for i in range(epochs):
    y = model(X_norm)
    loss = loss_fn(y, Y)

    optimizer.zero_grad()
    loss.backward()

    optimizer.step()

    if i % 5 == 0:
        print(f"epochs: {i}, loss: {loss}")

epochs: 0, loss: 73729.8984375
epochs: 5, loss: 60013.76171875
epochs: 10, loss: 48883.95703125
epochs: 15, loss: 39842.3984375
epochs: 20, loss: 32490.134765625
epochs: 25, loss: 26506.671875
epochs: 30, loss: 21633.837890625
epochs: 35, loss: 17663.193359375
epochs: 40, loss: 14426.1435546875
epochs: 45, loss: 11786.076171875
epochs: 50, loss: 9632.16015625
epochs: 55, loss: 7874.3701171875
epochs: 60, loss: 6439.498046875
epochs: 65, loss: 5267.9853515625
epochs: 70, loss: 4311.31884765625
epochs: 75, loss: 3529.98193359375
epochs: 80, loss: 2891.75244140625
epochs: 85, loss: 2370.3603515625
epochs: 90, loss: 1944.37109375
epochs: 95, loss: 1596.294189453125
epochs: 100, loss: 1311.8548583984375
epochs: 105, loss: 1079.3974609375
epochs: 110, loss: 889.4069213867188
epochs: 115, loss: 734.1132202148438
epochs: 120, loss: 607.1692504882812
epochs: 125, loss: 503.39111328125
epochs: 130, loss: 418.54376220703125
epochs: 135, loss: 349.16766357421875
epochs: 140, loss: 292.436126708984

In [52]:
# Test with a new house
test_house = torch.tensor([[1500, 3, 18], [1800, 4, 10]], dtype=torch.float32)
test_house = (test_house - X_mean) / X_std  # Normalize
test_price = model(test_house)
print(test_price)
for each in test_price:
    print(each.item())

tensor([[259.7364],
        [323.3285]], grad_fn=<AddmmBackward0>)
259.7364196777344
323.3285217285156


In [47]:
test_house = torch.tensor([[1500, 3, 18]], dtype=torch.float32)
test_house = (test_house - X_mean) / X_std  # Normalize
predicted_price = model(test_house).item()
print(f"\nPredicted price for house (1500 sq ft, 3 bedrooms, 18 years old): ${predicted_price*1000:.2f}")


Predicted price for house (1500 sq ft, 3 bedrooms, 18 years old): $259736.42
