In [3]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset

In [30]:
class HousePriceDataset(Dataset):
    def __init__(self):
        self.X = torch.tensor([
            [1400, 3, 20],
            [1600, 4, 15],
            [1700, 3, 10],
            [1875, 3, 5],
            [1100, 2, 25]
        ], dtype = torch.float32)

        self.Y = torch.tensor([[245], [312], [279], [308], [199]], dtype = torch.float32)

        self.X_mean, self.X_std = self.X.mean(dim = 0), self.X.std(dim = 0)

        self.X_norm =  (self.X - self.X_mean) / self.X_std

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X_norm[idx], self.Y[idx]

In [31]:
dataset = HousePriceDataset()
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

In [32]:
class HousePriceNN(nn.Module):
    def __init__(self):
        super(HousePriceNN, self).__init__()
        self.layer1 = nn.Linear(3,1)
    def forward(self, x):
        return self.layer1(x)

model = HousePriceNN()

epochs = 100
loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr = 0.01)

In [ ]:
class HousePriceNN2(nn.Module):
    def __init__(self):
        super(HousePriceNN2, self).__init__()
        self.layer1 = nn.Linear(3,1)
        
    def forward(self, x):
        return self.layer1(x)

model = HousePriceNN2()

epochs = 100
loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr = 0.01, weight_decay = 0.001)

In [79]:
import torch.nn.functional as F

class HousePriceNN3(nn.Module):
    def __init__(self):
        super(HousePriceNN3, self).__init__()
        self.layer1 = nn.Linear(3, 10)  # More neurons
        self.dropout = nn.Dropout(0)  # Dropout layer (30% neurons off)
        self.layer2 = nn.Linear(10, 1)  # Output layer

    def forward(self, x):
        x = F.relu(self.layer1(x))  # Apply ReLU
        x = self.dropout(x)  # Apply dropout during training
        x = self.layer2(x)  # Output layer
        return x


model = HousePriceNN3()

epochs = 200
loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr = 0.0001, weight_decay = 0.001)

for i in range(epochs):
    for X_batch, y_batch in dataloader:
        # print(X_batch, y_batch)
        y = model(X_batch)
        loss = loss_fn(y, y_batch)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    if i%5 == 0 or i == epochs-1:
        print(f"epoch: {i+1}, loss: {loss}")

epoch: 1, loss: 77595.5390625
epoch: 6, loss: 59285.078125
epoch: 11, loss: 72100.0703125
epoch: 16, loss: 73168.9921875
epoch: 21, loss: 32780.390625
epoch: 26, loss: 26569.328125
epoch: 31, loss: 64.86275482177734
epoch: 36, loss: 44.05049133300781
epoch: 41, loss: 422.224853515625
epoch: 46, loss: 42.879154205322266
epoch: 51, loss: 281.94281005859375
epoch: 56, loss: 40.3125
epoch: 61, loss: 35.94911575317383
epoch: 66, loss: 10.19159984588623
epoch: 71, loss: 10.938514709472656
epoch: 76, loss: 30.803380966186523
epoch: 81, loss: 26.347017288208008
epoch: 86, loss: 0.19996465742588043
epoch: 91, loss: 1.0888662338256836
epoch: 96, loss: 0.10549411922693253
epoch: 101, loss: 0.7182624340057373
epoch: 106, loss: 24.635129928588867
epoch: 111, loss: 23.782588958740234
epoch: 116, loss: 9.440878868103027
epoch: 121, loss: 0.012999117374420166
epoch: 126, loss: 14.176713943481445
epoch: 131, loss: 11.360980987548828
epoch: 136, loss: 0.14652204513549805
epoch: 141, loss: 8.167301177978

In [33]:
# 1
for i in range(epochs):
    for X_batch, y_batch in dataloader:
        y = model(X_batch)
        loss = loss_fn(y, y_batch)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    if i%5 == 0 or i == epochs-1:
        print(f"epoch: {i+1}, loss: {loss}")

epoch: 1, loss: 42556.38671875
epoch: 6, loss: 29990.765625
epoch: 11, loss: 28526.70703125
epoch: 16, loss: 15578.2861328125
epoch: 21, loss: 4962.6494140625
epoch: 26, loss: 2365.7353515625
epoch: 31, loss: 2257.65625
epoch: 36, loss: 1226.065185546875
epoch: 41, loss: 250.54209899902344
epoch: 46, loss: 410.78338623046875
epoch: 51, loss: 17.714265823364258
epoch: 56, loss: 234.2213134765625
epoch: 61, loss: 165.8080596923828
epoch: 66, loss: 7.092351913452148
epoch: 71, loss: 14.790371894836426
epoch: 76, loss: 71.22282409667969
epoch: 81, loss: 26.830427169799805
epoch: 86, loss: 52.32161331176758
epoch: 91, loss: 33.820640563964844
epoch: 96, loss: 38.929481506347656
epoch: 100, loss: 38.05061340332031


In [39]:
for i in range(epochs):
    for X_batch, y_batch in dataloader:
        y = model(X_batch)
        loss = loss_fn(y, y_batch)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    if i%5 == 0 or i == epochs-1:
        print(f"epoch: {i+1}, loss: {loss}")

epoch: 1, loss: 93394.40625
epoch: 6, loss: 50243.0546875
epoch: 11, loss: 24426.556640625
epoch: 16, loss: 9278.9521484375
epoch: 21, loss: 6091.498046875
epoch: 26, loss: 4443.41796875
epoch: 31, loss: 2124.875732421875
epoch: 36, loss: 457.39892578125
epoch: 41, loss: 936.5116577148438
epoch: 46, loss: 397.55987548828125
epoch: 51, loss: 16.184242248535156
epoch: 56, loss: 198.61959838867188
epoch: 61, loss: 177.32830810546875
epoch: 66, loss: 7.4042181968688965
epoch: 71, loss: 18.479398727416992
epoch: 76, loss: 66.51769256591797
epoch: 81, loss: 41.65424346923828
epoch: 86, loss: 59.60218811035156
epoch: 91, loss: 26.371145248413086
epoch: 96, loss: 34.91587829589844
epoch: 100, loss: 56.07755661010742


epoch: 1, loss: 91288.0546875
epoch: 6, loss: nan
epoch: 11, loss: nan
epoch: 16, loss: nan
epoch: 21, loss: nan
epoch: 26, loss: nan
epoch: 31, loss: nan
epoch: 36, loss: nan
epoch: 41, loss: nan
epoch: 46, loss: nan
epoch: 51, loss: nan
epoch: 56, loss: nan
epoch: 61, loss: nan
epoch: 66, loss: nan
epoch: 71, loss: nan
epoch: 76, loss: nan
epoch: 81, loss: nan
epoch: 86, loss: nan
epoch: 91, loss: nan
epoch: 96, loss: nan
epoch: 100, loss: nan


In [67]:
test_houses = torch.tensor([
    [1500, 3, 18],  # House 1
    [1800, 4, 10]   # House 2
], dtype=torch.float32)

test_houses = (test_houses - dataset.X_mean) / dataset.X_std
print(test_houses)

model(test_houses)

tensor([[-0.1176,  0.0000,  0.3795],
        [ 0.8902,  1.4142, -0.6325]])


tensor([[254.3834],
        [342.7014]], grad_fn=<AddmmBackward0>)

In [22]:
torch.save(model.state_dict(), 'house_price_state_dict.pth')

In [27]:
loaded_model = HousePriceNN()
loaded_model.load_state_dict(torch.load('house_price_state_dict.pth'))
loaded_model.eval()

HousePriceNN(
  (layer1): Linear(in_features=3, out_features=1, bias=True)
)

In [28]:
# Predict with the loaded model
test_houses = torch.tensor([
    [1500, 3, 18],  # House 1
    [1800, 4, 10]   # House 2
], dtype=torch.float32)

test_houses = (test_houses - dataset.X_mean) / dataset.X_std

print(test_houses)

tensor([[-0.1176,  0.0000,  0.3795],
        [ 0.8902,  1.4142, -0.6325]])


In [29]:
loaded_model(test_houses)

tensor([[261.1003],
        [325.2099]], grad_fn=<AddmmBackward0>)